import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

import { api } from "@app/utils/api";

export default function Home() {
  const getTasksQ = api.tasks.getAllTasks.useQuery();
  const addNewTaskMutation = api.tasks.addNewTasks.useMutation({
    onSuccess: () => {},
  });

  return (
    <>
      <Head>
        <title>T3 Todo App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" flex min-h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#24152c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-[2rem]">
            T3 Todo App
          </h1>

          <div className="card bg-neutral text-neutral-content w-96">
            <div className="card-body items-center text-center">
              <h2 className="card-title">New Task!</h2>

              <div className="card-actions justify-end">
                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">Task Title</span>
                  </label>
                  <input
                    type="text"
                    placeholder="Task title"
                    className="input input-bordered w-full max-w-xs"
                  />
                </div>

                <div className="form-control w-full">
                  <label className="label">
                    <span className="label-text">Description</span>
                  </label>
                  <textarea
                    className="textarea textarea-bordered h-24"
                    placeholder="Description "
                  />
                </div>
              </div>
              <button
                onClick={() => addNewTaskMutation.mutate()}
                className=" btn btn-primary w-full"
              >
                Add New Task
              </button>
            </div>
          </div>

          <div className="flex-col space-y-3">
            {getTasksQ.data?.data.map((item, key) => {
              return (
                <div key={key} className="rounded-md bg-white px-5 py-3">
                  <div className="flex items-center gap-3">
                    <div className="avatar">
                      <div className="w-10 rounded-xl">
                        <img src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
                      </div>
                    </div>
                    <div className="">
                      <h4 className="font-semibold text-black">
                        {item.task as string}
                      </h4>
                      <p className="font-normal text-black">
                        Description,Description,Description,Description{" "}
                      </p>
                    </div>
                  </div>
                </div>
              );
            })}

            <div className="rounded-md bg-white px-5 py-3">
              <div className="flex items-center gap-3">
                <div className="avatar">
                  <div className="w-10 rounded-xl">
                    <img src="https://daisyui.com/images/stock/photo-1534528741775-53994a69daeb.jpg" />
                  </div>
                </div>
                <div className="">
                  <h4 className="font-semibold text-black">TASK</h4>
                  <p className="font-normal text-black">
                    Description,Description,Description,Description{" "}
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  const { data: secretMessage } = api.example.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined },
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <p className="text-center text-2xl text-white">
        {sessionData && <span>Logged in as {sessionData.user?.name}</span>}
        {secretMessage && <span> - {secretMessage}</span>}
      </p>
      <button
        className="rounded-full bg-white/10 px-10 py-3 font-semibold text-white no-underline transition hover:bg-white/20"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>
    </div>
  );
}
